name: Run Workflow with Date

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      date_input:
        description: "Enter the date in DD-MM-YYYY format"
        required: true
        default: "10-11-2024"  # Optional default value

jobs:
  validate_date:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Date Format
        id: validate_date
        run: |
          # Extract day, month, and year from input
          DATE_INPUT="${{ github.event.inputs.date_input }}"
          DAY=${DATE_INPUT:0:2}
          MONTH=${DATE_INPUT:3:2}
          YEAR=${DATE_INPUT:6:4}
          
          # Check for format and logical validity
          if [[ ! "$DATE_INPUT" =~ ^[0-9]{2}-[0-9]{2}-[0-9]{4}$ ]]; then
            echo "Date format is invalid. Please use DD-MM-YYYY."
            exit 1
          elif ! date -d "$YEAR-$MONTH-$DAY" +"%d-%m-%Y" >/dev/null 2>&1; then
            echo "The date is invalid. Ensure the day is between 01-31, month between 01-12, and year is valid."
            exit 1
          else
            echo "Date format and range are valid."
          fi
        shell: bash
