name: Increase Version

on:
  push:
    branches:
      - master

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Bump Version
        uses: nnichols/maven-version-bump-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
